In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
train = pd.read_csv('data_train.csv')
#test = pd.read_csv('data_test.csv')

In [51]:
train = train.drop(['Unnamed: 0'],axis=1)
#test = test.drop(['Unnamed: 0'],axis=1)

In [52]:
train.head(15)

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,07:04:31,07:08:32,NaN,NaN,NaN,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,07:20:34,07:25:42,NaN,NaN,NaN,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,07:53:32,08:03:25,NaN,NaN,NaN,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,08:17:50,08:37:23,NaN,NaN,NaN,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,14:38:09,14:38:09,NaN,NaN,NaN,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07
5,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_5,15:02:31,15:18:33,NaN,NaN,NaN,3.744945e+06,-1.928183e+07,3.744785e+06,-1.928148e+07
6,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_0,14:29:23,14:29:23,0.000000,0.000000,0.000000,3.749450e+06,-1.926506e+07,3.749450e+06,-1.926506e+07
7,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_1,14:39:49,14:39:49,0.000000,0.000000,0.000000,3.749090e+06,-1.926726e+07,3.749090e+06,-1.926726e+07
8,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_2,14:50:14,14:50:14,0.507809,0.507809,0.507809,3.749042e+06,-1.926632e+07,3.749042e+06,-1.926632e+07
9,0000cf177130469eeac79f67b6bcf3df_9,traj_0000cf177130469eeac79f67b6bcf3df_9_3,15:00:32,15:29:48,1.149404,1.149404,1.149404,3.749088e+06,-1.926605e+07,3.749610e+06,-1.926594e+07
10,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_0,11:37:06,11:52:08,32.196255,32.196255,32.196255,3.771461e+06,-1.910413e+07,3.757004e+06,-1.929698e+07
11,0001f97b99a80f18f62e2d44e54ef33d_3,traj_0001f97b99a80f18f62e2d44e54ef33d_3_1,14:34:35,15:19:51,30.167742,30.167742,30.167742,3.758738e+06,-1.937594e+07,3.769687e+06,-1.914258e+07
12,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_1,09:56:08,09:56:08,NaN,NaN,NaN,3.765544e+06,-1.917227e+07,3.765544e+06,-1.917227e+07
13,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_2,10:17:00,10:17:00,NaN,NaN,NaN,3.766338e+06,-1.917967e+07,3.766338e+06,-1.917967e+07
14,0002124248b0ca510dea42824723ccac_31,traj_0002124248b0ca510dea42824723ccac_31_4,12:38:33,12:38:33,NaN,NaN,NaN,3.767863e+06,-1.917851e+07,3.767863e+06,-1.917851e+07

In [53]:
def temps(time_1, time_2):   
    sec1 = 3600*int(time_1[0:2]) + 60*int(time_1[3:5]) + int(time_1[6:8])
    sec2 = 3600*int(time_2[0:2]) + 60*int(time_2[3:5]) + int(time_2[6:8])                                                                                                                                   
    return (sec2-sec1)

def distance(x1,x2,y1,y2):
    dist = np.sqrt(((x2-x1)**2)+((y2-y1)**2))
    return dist

def velocity(dist, time):
    if time == 0:
        return 0
    else:
        v = dist / time
        return v

In [54]:
def conv(time_1):   
    sec1 = 3600*int(time_1[0:2]) + 60*int(time_1[3:5]) + int(time_1[6:8])                                                                                                                                
    return (sec1)

In [55]:
vec_conv =  np.vectorize(conv)

In [56]:
train.time_entry=vec_conv(train.time_entry)
train.time_exit=vec_conv(train.time_exit)

In [57]:
train.isnull().sum()

hash                  0
trajectory_id         0
time_entry            0
time_exit             0
vmax             557493
vmin             557493
vmean            543484
x_entry               0
y_entry               0
x_exit                0
y_exit                0
dtype: int64

In [58]:
train['vmean'][(train.time_entry==train.time_exit)] = 0
train['vmin'][(train.time_entry==train.time_exit)] = 0
train['vmax'][(train.time_entry==train.time_exit)] = 0

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [59]:
train.isnull().sum()

hash                  0
trajectory_id         0
time_entry            0
time_exit             0
vmax             284351
vmin             284351
vmean            270342
x_entry               0
y_entry               0
x_exit                0
y_exit                0
dtype: int64

In [60]:
train.describe()

,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
count,814262.000000,814262.000000,529911.000000,529911.000000,543920.000000,8.142620e+05,8.142620e+05,8.142620e+05,8.142620e+05
mean,39342.660226,39689.670820,1.096720,0.902521,1.025269,3.760411e+06,-1.922153e+07,3.760426e+06,-1.922181e+07
std,13993.416225,14025.396034,4.876927,4.454328,4.606952,8.974393e+03,7.632234e+04,8.904451e+03,7.515560e+04
min,0.000000,0.000000,-1.000000,-1.000000,-1.000000,3.741027e+06,-1.938291e+07,3.740998e+06,-1.937688e+07
25%,30610.000000,31043.000000,0.000000,0.000000,0.000000,3.755174e+06,-1.927454e+07,3.755359e+06,-1.927308e+07
50%,42262.000000,42606.000000,0.000000,0.000000,0.000000,3.760071e+06,-1.923020e+07,3.760076e+06,-1.923031e+07
75%,51175.000000,51530.000000,0.000000,0.000000,0.000000,3.767509e+06,-1.916999e+07,3.767455e+06,-1.917193e+07
max,57600.000000,57600.000000,138.000000,138.000000,138.000000,3.777099e+06,-1.904266e+07,3.777055e+06,-1.904666e+07

In [61]:
# test.describe()

In [62]:
# test.isnull().sum()

In [63]:
train['vmax'][(train.x_entry==train.x_exit)&(train.y_entry==train.y_exit)] = 0
train['vmin'][(train.x_entry==train.x_exit)&(train.y_entry==train.y_exit)] = 0
train['vmean'][(train.x_entry==train.x_exit)&(train.y_entry==train.y_exit)] = 0

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [64]:
#train['x_entry'][(train.time_entry==train.time_exit)]

In [65]:
train.isnull().sum()

hash                  0
trajectory_id         0
time_entry            0
time_exit             0
vmax             283391
vmin             283391
vmean            269397
x_entry               0
y_entry               0
x_exit                0
y_exit                0
dtype: int64

In [66]:
# fig,axes = plt.subplots()
# axes.scatter(x=train.index,y=train.vmean)
# plt.show()
# fig,axes = plt.subplots()
# axes.scatter(x=train.index,y=train.vmin)
# plt.show()
# fig,axes = plt.subplots()
# axes.scatter(x=train.index,y=train.vmax)
# plt.show()

In [67]:
# fig,axes = plt.subplots()
# axes.scatter(x=test.index,y=test.vmean)
# plt.show()
# fig,axes = plt.subplots()
# axes.scatter(x=test.index,y=test.vmin)
# plt.show()
# fig,axes = plt.subplots()
# axes.scatter(x=test.index,y=test.vmax)
# plt.show()

In [68]:
train.vmean = train.vmean.loc[(train.vmean<90) & (train.vmean>=0)]
train.vmax = train.vmean.loc[(train.vmax<90) & (train.vmax>=0)]
train.vmin = train.vmean.loc[(train.vmin<90) & (train.vmin>=0)]

In [69]:
train.head()

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,25471,25712,NaN,NaN,NaN,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,26434,26742,NaN,NaN,NaN,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,28412,29005,NaN,NaN,NaN,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,29870,31043,NaN,NaN,NaN,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,52689,52689,0.0,0.0,0.0,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07

In [70]:
train['city_center'] = 0

In [71]:
# 3750901.5068 ≤ 𝑥 ≤ 3770901.5068
# −19268905.6133 ≤ 𝑦 ≤ −19208905.6133

In [72]:
train['city_center'][(train.x_exit>=3750901.5068) & (train.x_exit<=3770901.5068)&(train.y_exit>=(-19268905.6133)) & (train.y_exit<=(-19208905.6133))]=1

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [73]:
train.head()

,hash,trajectory_id,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,x_exit,y_exit,city_center
0,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_0,25471,25712,NaN,NaN,NaN,3.751014e+06,-1.909398e+07,3.750326e+06,-1.913634e+07,0
1,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_1,26434,26742,NaN,NaN,NaN,3.743937e+06,-1.932247e+07,3.744975e+06,-1.931966e+07,0
2,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_2,28412,29005,NaN,NaN,NaN,3.744868e+06,-1.929356e+07,3.744816e+06,-1.929284e+07,0
3,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_3,29870,31043,NaN,NaN,NaN,3.744880e+06,-1.929229e+07,3.744809e+06,-1.929049e+07,0
4,0000a8602cf2def930488dee7cdad104_1,traj_0000a8602cf2def930488dee7cdad104_1_4,52689,52689,0.0,0.0,0.0,3.744909e+06,-1.928558e+07,3.744909e+06,-1.928558e+07,0

In [74]:
#train.dropna(inplace=True)
train['vmax']=train['vmax'].replace( np.NaN , train['vmax'].mean() )
train['vmin']=train['vmin'].replace( np.NaN , train['vmin'].mean() )
train['vmean']=train['vmean'].replace( np.NaN , train['vmean'].mean() )

In [75]:
#train2 = train.drop(['time_entry','time_exit'],axis=1)
train2 = train.drop(['trajectory_id','hash'],axis=1)
train2 = train2.drop(['x_exit','y_exit'],axis=1)

In [76]:
Y = train2['city_center']
X = train2.drop(['city_center'],axis=1)

In [77]:
from sklearn.ensemble import RandomForestClassifier

In [78]:
train2.head()

,time_entry,time_exit,vmax,vmin,vmean,x_entry,y_entry,city_center
0,25471,25712,1.034057,1.027016,1.064507,3.751014e+06,-1.909398e+07,0
1,26434,26742,1.034057,1.027016,1.064507,3.743937e+06,-1.932247e+07,0
2,28412,29005,1.034057,1.027016,1.064507,3.744868e+06,-1.929356e+07,0
3,29870,31043,1.034057,1.027016,1.064507,3.744880e+06,-1.929229e+07,0
4,52689,52689,0.000000,0.000000,0.000000,3.744909e+06,-1.928558e+07,0

In [79]:
from sklearn.preprocessing import normalize

#X = normalize(X, norm='l2', axis=1)

In [80]:
# clf = RandomForestClassifier(n_estimators=100,random_state=0)
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC

# clf = XGBClassifier()
clf = LinearSVC(verbose=True,random_state=0)

In [81]:
clf.fit(X,Y)

[LibLinear]

C:\Users\gouzm\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=True)

In [82]:
test = pd.read_csv('data_test.csv')
test = test.drop(['Unnamed: 0'],axis=1)
test.time_entry=vec_conv(test.time_entry)
test.time_exit=vec_conv(test.time_exit)

In [83]:
test['vmax'][(test.x_entry==test.x_exit)&(test.y_entry==test.y_exit)] = 0
test['vmin'][(test.x_entry==test.x_exit)&(test.y_entry==test.y_exit)] = 0
test['vmean'][(test.x_entry==test.x_exit)&(test.y_entry==test.y_exit)] = 0

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\gouzm\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [84]:
test['vmax']=test['vmax'].replace( np.NaN , test['vmax'].mean() )
test['vmin']=test['vmin'].replace( np.NaN , test['vmin'].mean() )
test['vmean']=test['vmean'].replace( np.NaN , test['vmean'].mean() )

In [85]:
test= test.loc[test.x_exit.isnull()]

In [86]:
test = test.drop(['x_exit','y_exit'],axis=1)
#test = test.drop(['time_entry','time_exit'],axis=1)

In [87]:
trajectory_id = test['trajectory_id']

In [88]:
test = test.drop(['hash','trajectory_id'],axis=1)

In [89]:
pred = clf.predict(test)

In [90]:
trajectory_id=trajectory_id.values

In [91]:
prediction = pd.DataFrame()

In [92]:
prediction['id']=trajectory_id
prediction['target']=pred

In [96]:
prediction.to_csv("EYChallenge_03.csv",index=False)

In [97]:
prediction

                                                id  target
0       traj_00032f51796fd5437b238e3a9823d13d_31_5       0
1      traj_000479418b5561ab694a2870cc04fd43_25_10       0
2       traj_000506a39775e5bca661ac80e3f466eb_29_5       0
3        traj_0005401ceddaf27a9b7f0d42ef1fbe95_1_4       0
4        traj_00063a4f6c12e1e4de7d876580620667_3_4       0
5       traj_0006535be25bb52dd06983447880c964_5_12       0
6       traj_0006f84bb33ec929d1cda7686f861d0a_31_3       0
7      traj_00093ae562586aed0e053b8431e8ace4_23_10       0
8       traj_000c739e444a70e1804d757a0580caaa_31_3       0
9       traj_000d479078af08618bddc7f09082b8c3_11_6       0
10     traj_000d6fba12a7d06defe90e3c9162c11e_29_11       0
11      traj_000efd6f95db39d6ba35027f02b5628f_9_20       0
12     traj_000feace3a33be9245e2783cdff467a8_15_12       0
13       traj_0011b48d0cf4f962833edd701afaf419_3_7       0
14      traj_001484cf0f956c316070be4b4c6352ff_29_7       0
15       traj_001d29060cfe35996cfeb141210ecbeb_9_2       0
16       traj_001dff40eab7eea1c10d0fadcea0c779_9_7       0
17      traj_001f9345a2979c553125c65499630f25_29_3       0
18      traj_002447d99e8f6c3bc6c1329140979a91_25_7       0
19      traj_002531dea45cd4059e92099630ebf775_3_10       0
20      traj_00265578639bd4d35a3524a1463d98bb_31_8       0
21      traj_0026d48a63f219dc359f1131805909bf_31_5       0
22      traj_002f7d1d09d2af27ee5a6d0fa4e91c96_29_8       0
23      traj_0032262ce8e9e5e3750f306a2ace8d4a_25_4       0
24      traj_0033b16d18ce91c89eafacb1cb3a5a44_11_4       0
25     traj_00351550555ffcb00b52d21bcaabfadf_31_11       0
26     traj_003539963b1eebf6088d3d5302e45232_31_12       0
27      traj_00390d9128b5d9c7ba1b32c8babb6c24_11_2       0
28       traj_003a9e30d316e8fc524ac36f9deac690_1_5       0
29       traj_003d9b2742ddcd1a37717c524135b3d4_3_2       0
...                                            ...     ...
33485    traj_ffb5f2a2b26610380802fdcd9bad632c_1_3       0
33486   traj_ffb6f598b7194db26036098ac007acc2_19_9       0
33487    traj_ffb710d354ecbe6163aa2ee5e0883447_9_9       0
33488   traj_ffb78d018356f592ae576c9628a45484_25_6       0
33489    traj_ffb9db79c6b96d152334efa2c1d06fab_3_7       0
33490  traj_ffbc7807308dedf49523080af5d79eed_29_15       0
33491   traj_ffbf4376c763fac389a8846072d07799_23_2       0
33492   traj_ffc4a4d656ea7e6bce1775aa23d48d48_31_7       0
33493   traj_ffc4e987fb10a9a768a98c464540bcb3_23_2       0
33494   traj_ffc880cc98b30c6905a1bac96153de0c_23_7       0
33495   traj_ffca386c11dbd2007a3e58ccb6a782e0_15_5       0
33496   traj_ffcb11743cc9dc1129fdfb207ca5375b_15_3       0
33497    traj_ffcdb92dfa0b6771787205ff32a43d7d_1_8       0
33498   traj_ffce1404987f65b6807f600e9c786ac8_5_15       0
33499    traj_ffd18e6378c5384cfb135c569e0ef8f2_9_4       0
33500   traj_ffd395ec3142de6fa43c6c4c8196191c_11_8       0
33501  traj_ffd3d9d488e22ac1558536d56cef0c1b_23_13       0
33502  traj_ffd6099333016778d39013a2e5f4c0e3_29_11       0
33503    traj_ffd9243bfaa2802879e77b08c3c99c81_9_8       0
33504   traj_ffd97ad509d7b0c17b40d93cfb8def44_31_3       0
33505    traj_ffe12e09e01554bc5bcc2661290c11d9_3_3       0
33506   traj_ffe474fc44b2a5c0b5f733c51d27ab35_31_2       0
33507  traj_ffe4cfa385932e1db09e85d8bd73609d_11_10       0
33508   traj_ffe54b47c077d8c5c27dd608ffac09d1_9_11       0
33509    traj_ffe7b16199fab37e6c1f4eae7d2e5d64_1_3       0
33510  traj_ffe98f6e0adf12f9c7b51c4e9607a87a_15_13       0
33511   traj_fff607ecd3f8d3dcb65791e8b4c22a5f_3_25       0
33512   traj_fff813b56230c2f026f783f5b9f9ca90_19_0       0
33513  traj_fff9400843a88c3bfe52e7ce8bf97316_19_17       0
33514   traj_fff9552047b095e8242b4913f3289a26_25_7       0

[33515 rows x 2 columns]

In [ ]:
# a=pd.Series(clf.feature_importances_)
# a.nlargest(10).plot(kind='barh')

In [ ]:
train.describe()

In [ ]:
test.isnull().sum()

In [ ]:
train.vmean.unique()